#!/bin/bash
#
# retry running ssbackup if previous attempt failed
# can be used by pm to run at thaw/resume
# also via cron at shorter than intented interval (i.e. check hourly for daily backup)

install_dir=$(dirname `realpath $0`)
my_name=`basename $0`
ext=""
if [[ $my_name =~ inc ]]; then
    ext="inc"
fi

# find backup schedule and check with latest succesful backup:
if [ -x $install_dir/check_backup_schedule ]; then
    echo "checking schedule:"
    if $install_dir/check_backup_schedule "$@" ; then
	# no full backup needed, check for incremental:
	echo "no full backup needed, check for incremental"
	if $install_dir/check_backup_schedule inc; then
	    # no incremental backup needed:
	    echo "no incremental backup needed"
	    exit;
	else
	    # incremental needed:
	    echo "incremental needed"
	    ext="inc"
	fi
    else
	# full needed:
	echo "full needed"
	true
    fi
    echo "done checking schedule:"
fi

for backup in $install_dir/ssbackup $install_dir/sbackup-launch /usr/bin/sbackup /usr/sbin/sbackupd; do
    if [ -x $backup ]; then
	echo "Launching $backup $ext $@"
	$backup "$ext" "$@" || echo Failed && break
    fi
done

#last line
